### ISSUE TITLE
Plugin won't work on local machine

### ISSUE THREAD

**Issue by Spydr331** [focuslabllc/craft-cheat-sheet#42]
I am currently running on "localhost:88/craft/public" off of MAMP. I downloaded the site yesterday and downloaded this plugin today as I learn more of craft. I installed and enabled the plugin but when I go to "http://localhost:88/Craft/public/cheatsheet" it gives me a 404 page.

Does the plugin not work locally? I updated the site url in general settings to be "http://localhost:88/Craft/public" but not sure if there are any other settings for my site that are not correct right now maybe?

**Comment by erikreagan** [comment]
The plugin only works when `devMode` is enabled. Can you double check to see if that's the case on your site?

**Comment by erikreagan** [comment]
Two links that might be helpful:

- https://craftcms.com/support/dev-mode
- https://craftcms.com/docs/config-settings#devMode

**Comment by Spydr331** [comment]
I must have missed the part where it said to activate dev mode, thank you, that was the solution

**Comment by erikreagan** [comment]
Excellent! Happy cheating :)
