### ISSUE TITLE
Plugin update not registering with Craft control panel update page

### ISSUE THREAD

**Issue by jayhlee** [focuslabllc/craft-cheat-sheet#44]
I updated Cheatsheet to the latest version 1.2.1, but the update doesn't seem to register with the Craft control page. I tried uninstalling altogether and installing again, but I get the same message. 

![update](https://cloud.githubusercontent.com/assets/25807445/24520102/1b93ed88-153c-11e7-93ee-4f369c8bc115.png)

**Comment by erikreagan** [comment]
I believe this was fixed within the past 24 hours (#43). Can you download a fresh copy and try again?

**Comment by jayhlee** [comment]
Thanks, Erik! It works now.
