### ISSUE TITLE
404 After Install

### ISSUE THREAD

**Issue by dpanfili** [focuslabllc/craft-cheat-sheet#46]
After installing the plugin and setting the url path (in my instance just /cheat ), I'm getting a 404 when trying to reach that page. Running locally through MAMP if that helps troubleshoot. Also using free version of Craft.

**Comment by erikreagan** [comment]
Do other dynamic urls load like entries you've created in sections?

**Comment by dpanfili** [comment]
Dynamic urls only show correctly if devMode is set to true. If set to false, the they return 404s.

**Comment by erikreagan** [comment]
Is the same true for the cheat sheet url? Does it work for you with devMode set to true?

**Comment by erikreagan** [comment]
Clarification: the Cheat Sheet is designed to only work when devMode is turned on. So what you're experiencing, if I understand it correctly, is intended.

https://github.com/focuslabllc/craft-cheat-sheet/blob/2eebebcac78024b2afb04f7920a231ed708fc3b6/cheatsheet/controllers/CheatSheet_RoutesController.php#L24

Does that help?

**Comment by dpanfili** [comment]
Yes, helps for sure. Sorry for the delay in response here. All good. Closing out. Thanks!
