### ISSUE TITLE
Page not found /cheatsheet

### ISSUE THREAD

**Issue by asparkam** [focuslabllc/craft-cheat-sheet#47]
Hello! I do everything according to this i[nstruction](https://github.com/focuslabllc/craft-cheat-sheet#installing-craft-cheat-sheet): I move the folder cheatsheet into plugins, then click install. Plugin is enabled, I'm trying to go to: http://sitename.dev/cheatsheet, but the page was not found. I changed the paths in the settings - it did not help. 
What's wrong?

Craft version: 2.6.3003 - clean and just installed and downloaded from official site.

**Comment by asparkam** [comment]
Sorry, my fault. I'm not enable 'devMode' => true in craft config. May be put the note about it into install instruction?

**Comment by erikreagan** [comment]
I think adding the instruction to the install section makes sense. We'll work that in. Thanks!
