### ISSUE TITLE
Craft does not detect plugin

### ISSUE THREAD

**Issue by eheiser** [focuslabllc/craft-cheat-sheet#50]
Craft CMS 2.6.3010, fresh install with client license. The cheatsheet folder is present in the plugin folder but the Craft control panel won't find it. Any idea? Never had this happen before.

**Comment by eheiser** [comment]
never mind, was looking in the wrong install. Long day :)

**Comment by erikreagan** [comment]
No worries, @eheiser. Glad it's sorted. Good to hear from you either way.

Cheers :)

**Comment by eheiser** [comment]
Cheers mate!
