### ISSUE TITLE
Craft 3 version?

### ISSUE THREAD

**Issue by eheiser** [focuslabllc/craft-cheat-sheet#52]
Will there be a Craft3 version in the plugin store at some point?
Cheers!

**Comment by j-greig** [comment]
Just wrote "Is there a way to autogenerate a basic template that outputs all of the content for an entry?" then remembered this plugin : )

**Comment by guyinpv** [comment]
Also would like a Craft 3 version. I don't have a "plugins" folder. I'm assuming this would have to be converted to a Composer project. Re #51

**Comment by erikreagan** [comment]
@eheiser @j-greig @guyinpv The Craft 3 version can be found in the plugin store now!
