### ISSUE TITLE
Twig Runtime Error V2.0.0

### ISSUE THREAD

**Issue by wsydney76** [focuslabllc/craft-cheat-sheet#55]
When calling http://demo.local/cheatsheet there is a twig runtime error:

`Impossible to invoke a method ("strRepeat") on a string variable ("_includes/fieldMacros.twig").`

in \vendor\focuslabllc\craft-cheat-sheet\src\templates\frontEnd\_includes\fieldMacros.twig line 667.

  `~ _self.strRepeat(' ', max(rowWhitespace) - col.handle|length)`

Removing this line helps, could not notice anything wrong on the output at a first glance.

Thanks.

**Comment by erikreagan** [comment]
@wsydney76 I just published `2.0.1` which should fix this. Thanks!
