### ISSUE TITLE
/cheatsheet errors out with a missing template?

### ISSUE THREAD

**Issue by MattWilcox** [focuslabllc/craft-cheat-sheet#58]
Attempting to go to /cheatsheet produces a page with this error:

Unable to find the template “_includes/fieldMacros.twig”.

in the file

/craft/vendor/focuslabllc/craft-cheat-sheet/src/templates/frontEnd/cheatsheet.html

on line 143

**Comment by jayhlee** [comment]
Got the same error, too.

**Comment by erikreagan** [comment]
Same as #54. Closing this one and will continue the thread there.
